[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
esportdreams = "E2NXyH74LV4ibLRJrm9EBQK2fcoJCXiLY5k16RxtRDop"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/wanaqil/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"