[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dummy_stake = "HbxgLaoyRvYhzQoMgf9xKG9A2pdBcr6bkmyP7DBUFQE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/wanaqil/devnet-wallet.json"

[scripts]
test = "run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"